"""What a request costs, in the units providers actually meter.

A cost is a vector, not a number. Providers meter requests, input tokens and
output tokens separately, on separate limits, and some of them meter further
categories such as cached input or reasoning tokens. Collapsing those into one
number loses exactly the information admission control needs.
"""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Literal

Meter = Literal["requests", "input_tokens", "output_tokens", "total_tokens"]
"""Which part of a cost a rate limit counts."""


@dataclass(frozen=True)
class Cost:
    """The metered cost of one request.

    Every field is a count, never a price. This library has no opinion about
    money, and a token that is free still occupies a limit.

    Attributes:
        input_tokens: Tokens sent to the model. Countable before the call.
        output_tokens: Tokens generated by the model. Not knowable until the
            call completes, which is the whole difficulty this library exists
            to handle.
        requests: Almost always one. It is a field because request per minute
            limits meter it, and because a batch endpoint may not be one.
        extra: Provider specific categories that sit on their own limits, such
            as `cached_input` or `reasoning`. Empty for most providers.

    Example:
        >>> reserved = Cost(input_tokens=12_400, output_tokens=1_180)
        >>> actual = Cost(input_tokens=12_400, output_tokens=415)
        >>> reserved - actual
        Cost(input_tokens=0, output_tokens=765, requests=0, extra={})
        >>> actual.total_tokens
        12815
    """

    input_tokens: int = 0
    output_tokens: int = 0
    requests: int = 1
    extra: Mapping[str, int] = field(default_factory=dict)

    def metered(self, meter: Meter) -> int:
        """Return the part of this cost that `meter` counts.

        A rate limit meters one thing. Requests per minute counts requests and
        ignores tokens entirely; input tokens per minute counts only what was
        sent. Pulling the right number out is a lookup, and it lives here
        because this is where the fields are.

        Example:
            >>> cost = Cost(input_tokens=100, output_tokens=25)
            >>> cost.metered("requests"), cost.metered("output_tokens")
            (1, 25)
        """
        if meter == "requests":
            return self.requests
        if meter == "input_tokens":
            return self.input_tokens
        if meter == "output_tokens":
            return self.output_tokens
        return self.total_tokens

    @property
    def total_tokens(self) -> int:
        """Input plus output, for providers that meter one combined limit.

        Categories in `extra` are excluded. They exist precisely because the
        provider counts them apart from the ordinary totals, so folding them
        back in would double count.
        """
        return self.input_tokens + self.output_tokens

    def __sub__(self, other: Cost) -> Cost:
        """Subtract componentwise, keeping the sign.

        Settlement is a difference: what was reserved minus what was actually
        used. A positive component is unused capacity to credit back and a
        negative one is an overrun to repay, so components are never clamped
        at zero. Clamping here would silently discard every overrun.

        Example:
            >>> Cost(output_tokens=100) - Cost(output_tokens=250)
            Cost(input_tokens=0, output_tokens=-150, requests=0, extra={})
        """
        if not isinstance(other, Cost):
            return NotImplemented
        keys = set(self.extra) | set(other.extra)
        extra = {key: self.extra.get(key, 0) - other.extra.get(key, 0) for key in sorted(keys)}
        return Cost(
            input_tokens=self.input_tokens - other.input_tokens,
            output_tokens=self.output_tokens - other.output_tokens,
            requests=self.requests - other.requests,
            extra=extra,
        )


DistributionKind = Literal["point", "bounded"]


@dataclass(frozen=True)
class Distribution:
    """A prediction of how many output tokens a request will produce.

    Output length is the one part of a request's cost that cannot be known
    before the call, so it is represented as a distribution rather than a
    number. Admission reserves a quantile of it, which is what makes reserving
    conservatively affordable: the surplus is credited back the moment the real
    figure is known.

    Construct one through `point` or `bounded_by` rather than directly. Both
    currently answer every quantile with the same number, and they are separate
    kinds because they mean different things to a reader and because later
    stages treat a bound as a fallback rather than a belief.

    Example:
        >>> known = Distribution.point(300)
        >>> known.quantile(0.5), known.quantile(0.9)
        (300, 300)
        >>> Distribution.bounded_by(4096).quantile(0.9)
        4096
    """

    kind: DistributionKind
    value: int

    def __post_init__(self) -> None:
        """Reject a negative token count, which no provider can produce."""
        if self.value < 0:
            message = f"An output token count cannot be negative, got {self.value}."
            raise ValueError(message)

    @classmethod
    def point(cls, value: int) -> Distribution:
        """Predict exactly `value` output tokens.

        Use this when output length is genuinely known, for instance a
        classifier that answers with a single label. It exists so that a user
        who knows the answer is not forced through a probabilistic API.
        """
        return cls(kind="point", value=value)

    @classmethod
    def bounded_by(cls, max_tokens: int) -> Distribution:
        """Predict nothing, and reserve the worst case of `max_tokens`.

        The safe, uninformed baseline, and what a provider that meters on the
        requested maximum does itself. It is correct and it is expensive: if
        the maximum is 4096 and the median output is 300, it reserves roughly
        thirteen times what is used.
        """
        return cls(kind="bounded", value=max_tokens)

    def quantile(self, q: float) -> int:
        """Return the output length at quantile `q`, where `q` is in [0, 1].

        Raises:
            ValueError: if `q` is outside [0, 1].
        """
        if not 0.0 <= q <= 1.0:
            message = f"A quantile must be between 0 and 1 inclusive, got {q}."
            raise ValueError(message)
        return self.value


@dataclass(frozen=True)
class Estimate:
    """What a request is predicted to cost, before it is made.

    The asymmetry between the two token fields is the point. Input is counted,
    output is predicted, and pretending otherwise is how limiters end up either
    reserving thirteen times too much or discovering the overshoot from a
    provider error.

    Attributes:
        input: Exact input tokens, countable before the call.
        output: Predicted output length.
        model: The model this estimate is for, when known. Later stages key
            learned statistics on it.

    Example:
        >>> estimate = Estimate(input=12_400, output=Distribution.point(415))
        >>> estimate.input, estimate.output.quantile(0.9)
        (12400, 415)
    """

    input: int
    output: Distribution
    model: str | None = None

    def __post_init__(self) -> None:
        """Reject a negative input count, which no prompt can have."""
        if self.input < 0:
            message = f"An input token count cannot be negative, got {self.input}."
            raise ValueError(message)


CHARACTERS_PER_TOKEN = 3.6
"""Characters per token, averaged over English prose.

Counting tokens exactly needs a tokenizer, which is a heavy dependency per
model, and the quickstart has to work with nothing installed. This divisor is
within roughly ten to fifteen percent for English and drifts further for code
and for languages that do not use a Latin script.

Undercounting is not a correctness problem here. The real figure replaces the
estimate at settlement, exactly like a mistaken output prediction does.
"""

# ponytail: a flat guess, wrong for both a one word classification and a long
# report. Superseded per route once the estimator learns from settled requests.
# Pass max_tokens, or an explicit Estimate, to bypass it entirely.
DEFAULT_MAX_OUTPUT_TOKENS = 1024
"""Output tokens reserved when the caller names no maximum."""


def _text_length(part: object) -> int:
    """Return the character count of anything a caller might call a prompt."""
    if isinstance(part, str):
        return len(part)
    if isinstance(part, Mapping):
        content = part.get("content")
        if content is None:
            return 0
        return _text_length(content)
    if isinstance(part, Sequence):
        total = 0
        for item in part:
            total += _text_length(item)
        return total
    return len(str(part))


def default_estimate(
    prompt: str | Sequence[object] | None = None,
    *,
    max_tokens: int | None = None,
    model: str | None = None,
) -> Estimate:
    """Estimate a request's cost from its prompt and its requested output length.

    Input is counted with a character heuristic, so it is approximate and
    documented as such. Output is reserved at the requested maximum, which is
    the safe and uninformed answer.

    Args:
        prompt: A string, or a sequence of message mappings in the shape the
            provider SDKs use. Anything else is stringified and measured.
        max_tokens: The requested output limit. Defaults to
            `DEFAULT_MAX_OUTPUT_TOKENS` when absent.
        model: Recorded on the estimate when known.

    Example:
        >>> default_estimate("hello there", max_tokens=256)
        Estimate(input=4, output=Distribution(kind='bounded', value=256), model=None)
        >>> default_estimate([{"role": "user", "content": "hi"}], max_tokens=10).input
        1
        >>> default_estimate().output.value == DEFAULT_MAX_OUTPUT_TOKENS
        True

    Raises:
        ValueError: if `max_tokens` is negative.
    """
    if max_tokens is not None and max_tokens < 0:
        message = f"max_tokens cannot be negative, got {max_tokens}."
        raise ValueError(message)
    characters = _text_length(prompt) if prompt is not None else 0
    reserved_output = DEFAULT_MAX_OUTPUT_TOKENS if max_tokens is None else max_tokens
    return Estimate(
        input=math.ceil(characters / CHARACTERS_PER_TOKEN),
        output=Distribution.bounded_by(reserved_output),
        model=model,
    )
