"""What a request costs, in the units providers actually meter.

A cost is a vector, not a number. Providers meter requests, input tokens and
output tokens separately, on separate limits, and some of them meter further
categories such as cached input or reasoning tokens. Collapsing those into one
number loses exactly the information admission control needs.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Cost:
    """The metered cost of one request.

    Every field is a count, never a price. This library has no opinion about
    money, and a token that is free still occupies a limit.

    Attributes:
        input_tokens: Tokens sent to the model. Countable before the call.
        output_tokens: Tokens generated by the model. Not knowable until the
            call completes, which is the whole difficulty this library exists
            to handle.
        requests: Almost always one. It is a field because request per minute
            limits meter it, and because a batch endpoint may not be one.
        extra: Provider specific categories that sit on their own limits, such
            as `cached_input` or `reasoning`. Empty for most providers.

    Example:
        >>> reserved = Cost(input_tokens=12_400, output_tokens=1_180)
        >>> actual = Cost(input_tokens=12_400, output_tokens=415)
        >>> reserved - actual
        Cost(input_tokens=0, output_tokens=765, requests=0, extra={})
        >>> actual.total_tokens
        12815
    """

    input_tokens: int = 0
    output_tokens: int = 0
    requests: int = 1
    extra: Mapping[str, int] = field(default_factory=dict)

    @property
    def total_tokens(self) -> int:
        """Input plus output, for providers that meter one combined limit.

        Categories in `extra` are excluded. They exist precisely because the
        provider counts them apart from the ordinary totals, so folding them
        back in would double count.
        """
        return self.input_tokens + self.output_tokens

    def __sub__(self, other: Cost) -> Cost:
        """Subtract componentwise, keeping the sign.

        Settlement is a difference: what was reserved minus what was actually
        used. A positive component is unused capacity to credit back and a
        negative one is an overrun to repay, so components are never clamped
        at zero. Clamping here would silently discard every overrun.

        Example:
            >>> Cost(output_tokens=100) - Cost(output_tokens=250)
            Cost(input_tokens=0, output_tokens=-150, requests=0, extra={})
        """
        if not isinstance(other, Cost):
            return NotImplemented
        keys = set(self.extra) | set(other.extra)
        extra = {key: self.extra.get(key, 0) - other.extra.get(key, 0) for key in sorted(keys)}
        return Cost(
            input_tokens=self.input_tokens - other.input_tokens,
            output_tokens=self.output_tokens - other.output_tokens,
            requests=self.requests - other.requests,
            extra=extra,
        )
